# Generated by Django 3.0.5 on 2020-07-01 14:16

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20200621_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='uploads/% Y/% m/% d/')),
            ],
        ),
    ]
